import { Job } from "@/shared/types/job";

const mockJobs: Job[] = [
    {
        id: '1',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        numberOfApplicants: 1,
        capacity: 20,
        categoryNames: ['IT', 'Software', 'Engineering'],
        company: {
            id: '1',
            name: "Tech Corp",
            description: "We are a tech company that builds software for the web",
            location: "San Francisco, CA",
            website: "https://techcorp.com",
            size: "100",
            rating: 4.5,
            industry: "Software",
        }
    }, 
    {
        id: '2',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        numberOfApplicants: 10,
        capacity: 20,
        categoryNames: ['IT', 'Software', 'Engineering'],
        company: {
            id: '1',
            name: "Tech Corp",
            description: "We are a tech company that builds software for the web",
            location: "San Francisco, CA",
            website: "https://techcorp.com",
            size: "100",
            rating: 4.5,
            industry: "Software",
        }
    },
    {
        id: '3',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        numberOfApplicants: 15,
        capacity: 20,
        categoryNames: ['IT', 'Software', 'Engineering'],
        company: {
            id: '1',
            name: "Tech Corp",
            description: "We are a tech company that builds software for the web",
            location: "San Francisco, CA",
            website: "https://techcorp.com",
            size: "100",
            rating: 4.5,
            industry: "Software",
        }
    },
    {
        id: '4',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        numberOfApplicants: 20,
        capacity: 20,
        categoryNames: ['IT', 'Software', 'Engineering'],
        company: {
            id: '1',
            name: "Tech Corp",
            description: "We are a tech company that builds software for the web",
            location: "San Francisco, CA",
            website: "https://techcorp.com",
            size: "100",
            rating: 4.5,
            industry: "Software",
        }
    },
    {
        id: '5',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        numberOfApplicants: 0,
        capacity: 20,
        categoryNames: ['IT', 'Software', 'Engineering'],
        company: {
            id: '1',
            name: "Tech Corp",
            description: "We are a tech company that builds software for the web",
            location: "San Francisco, CA",
            website: "https://techcorp.com",
            size: "100",
            rating: 4.5,
            industry: "Software",
        }
    },
    {
        id: '6',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        numberOfApplicants: 10,
        capacity: 20,
        categoryNames: ['IT', 'Software', 'Engineering'],
        company: {
            id: '1',
            name: "Tech Corp",
            description: "We are a tech company that builds software for the web",
            location: "San Francisco, CA",
            website: "https://techcorp.com",
            size: "100",
            rating: 4.5,
            industry: "Software",
        }
    },
    {
        id: '7',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        numberOfApplicants: 10,
        capacity: 20,
        categoryNames: ['IT', 'Software', 'Engineering'],
        company: {
            id: '1',
            name: "Tech Corp",
            description: "We are a tech company that builds software for the web",
            location: "San Francisco, CA",
            website: "https://techcorp.com",
            size: "100",
            rating: 4.5,
            industry: "Software",
        }
    },
    {
        id: '8',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        numberOfApplicants: 10,
        capacity: 20,
        categoryNames: ['IT', 'Software', 'Engineering'],
        company: {
            id: '1',
            name: "Tech Corp",
            description: "We are a tech company that builds software for the web",
            location: "San Francisco, CA",
            website: "https://techcorp.com",
            size: "100",
            rating: 4.5,
            industry: "Software",
        }
    },
    {
        id: '9',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        numberOfApplicants: 10,
        capacity: 20,
        categoryNames: ['IT', 'Software', 'Engineering'],
        company: {
            id: '1',
            name: "Tech Corp",
            description: "We are a tech company that builds software for the web",
            location: "San Francisco, CA",
            website: "https://techcorp.com",
            size: "100",
            rating: 4.5,
            industry: "Software",
        }
    }
]
export default mockJobs;