import { Job } from "@/shared/types/common";

const mockJobs: Job[] = [
    {
        id: '1',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        companyName: "Tech Corp",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
        
    }, 
    {
        id: '2',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        companyName: "Tech Corp",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
    },
    {
        id: '3',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        companyName: "Tech Corp",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
    },
    {
        id: '4',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        companyName: "Tech Corp",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],

    },
    {
        id: '5',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        companyName: "Tech Corp",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
    },
    {
        id: '6',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        companyName: "Tech Corp",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
    },
    {
        id: '7',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        companyName: "Tech Corp",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],

    },
    {
        id: '8',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        companyName: "Tech Corp",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
    },
    {
        id: '9',
        jobTitle: "Software Engineer",
        description: "We are looking for a software engineer with 3 years of experience in React and Node.js",
        location: "San Francisco, CA",
        companyName: "Tech Corp",
        jobType: "Full-Time",
        postedDate: "2024-01-01",
        expiryDate: "2024-01-01",
        experienceLevel: "Senior",
        skillNames: ["React", "Node.js", "JavaScript"],
    }
]
export default mockJobs;